### ISSUE TITLE
look ahead masking

### ISSUE THREAD

**Issue by abhandari73** [LiamMaclean216/Pytorch-Transfomer#1]
Hi, 
Why did you not implement look ahead masking in your model. 
I am new to transformers.
Regards
Arjun

**Comment by maxwrf** [comment]
That would also be my question... But I guess as in this implementation, the input sequence is also fed into decoder, there is no reason to mask anything?

**Comment by LIngerwsk** [comment]
Hi,
because the input sequence is also fed into the decoder, the model should implement look ahead masking to mask the "future" information. 
Did you modified your code? Because the code looks not have a good reproduction of the paper.
I am looking forward for you reply. Thank you very much.

**Comment by LiamMaclean216** [comment]
Masking is effectively accomplished with the loop
`for b in range(-10- enc_seq_len, 10 - enc_seq_len):`
