### ISSUE TITLE
Training on GPU

### ISSUE THREAD

**Issue by tayibgetup** [LiamMaclean216/Pytorch-Transfomer#8]
Hi, first of all, thank you for the amazing work you have done. I have been playing with this architecture for a while now and have taken huge inspiration from your code. I have been trying to train this model on GPU but always end up with an error of **RuntimeError: Tensor for argument #3 'mat2' is on CPU, but expected it to be on GPU (while checking arguments for addmm)**. Do you know how this can be solved?

**Comment by LiamMaclean216** [comment]
Issue seems to have been solved in https://github.com/LiamMaclean216/Pytorch-Transfomer/issues/4

Are you running on the latest commit?
